In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,50,15)

In [3]:
x

array([23, 25, 28, 49, 39, 19, 31, 10, 40,  8, 11, 43, 19, 37,  1])

In [5]:
x[0]

23

In [6]:
x[-1]

1

In [7]:
x[0:5]

array([23, 25, 28, 49, 39])

In [8]:
x = np.random.randint(1,50,(5,5))

In [9]:
x

array([[26, 32, 22, 41, 20],
       [27,  9,  6, 23, 31],
       [47, 20, 25,  6, 17],
       [23, 31, 37, 19, 29],
       [49, 15,  9, 36, 24]])

In [10]:
x[0]

array([26, 32, 22, 41, 20])

In [11]:
x[1]

array([27,  9,  6, 23, 31])

In [12]:
x[0][0]

26

In [13]:
x[0][4]

20

In [14]:
x[:,0]

array([26, 27, 47, 23, 49])

In [15]:
# all rows, but 0th column only
x[:,0:1]

array([[26],
       [27],
       [47],
       [23],
       [49]])

In [17]:
x[:,2:3]

array([[22],
       [ 6],
       [25],
       [37],
       [ 9]])

In [18]:
x[0:2]

array([[26, 32, 22, 41, 20],
       [27,  9,  6, 23, 31]])

In [19]:
# all rows, but 0,1 and 2 column
x[:,0:3]

array([[26, 32, 22],
       [27,  9,  6],
       [47, 20, 25],
       [23, 31, 37],
       [49, 15,  9]])

In [20]:
# all rows, but 1, 3 and 4th column
x[:,[1,3,4]]

array([[32, 41, 20],
       [ 9, 23, 31],
       [20,  6, 17],
       [31, 19, 29],
       [15, 36, 24]])

In [21]:
# 3 rows, 3 columns
x[0:3,0:3]

array([[26, 32, 22],
       [27,  9,  6],
       [47, 20, 25]])

In [22]:
# 0, 2 and 3rd row, but 0 to 3 columns
x[[0,2,3], 0:3]

array([[26, 32, 22],
       [47, 20, 25],
       [23, 31, 37]])

In [23]:
np.array([[[2,4,5],[5,3,6]],[[5,7,2],[1,3,8]],[[1,4,2],[5,4,7]]])

array([[[2, 4, 5],
        [5, 3, 6]],

       [[5, 7, 2],
        [1, 3, 8]],

       [[1, 4, 2],
        [5, 4, 7]]])