In [1]:
import numpy as np

### Ways to Create Array

In [2]:
# 1. using np.array()
x1 = np.array([3,4,5,2,4,7,8])

In [3]:
x1

array([3, 4, 5, 2, 4, 7, 8])

In [4]:
np.array(list([3,4,5,6]))

array([3, 4, 5, 6])

In [5]:
print(np.array(list([3,4,5,6])))

[3 4 5 6]


In [22]:
# 2d array
x_2d = np.array([[3,4,5,7,7,3],[1,2,35,1,14,12],[5,4,6,7,6,4],[2,4,6,7,5,3]])

In [23]:
x_2d

array([[ 3,  4,  5,  7,  7,  3],
       [ 1,  2, 35,  1, 14, 12],
       [ 5,  4,  6,  7,  6,  4],
       [ 2,  4,  6,  7,  5,  3]])

In [6]:
# 2. using np.arange(start, stop, step)
x2 = np.arange(1,21,2)

In [7]:
x2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
# 3. using np.linspace(start, stop, num=50, retstep=False)
x3 = np.linspace(1,20)

In [9]:
x3

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [10]:
np.linspace(1,20, retstep=True, num=15)

(array([ 1.        ,  2.35714286,  3.71428571,  5.07142857,  6.42857143,
         7.78571429,  9.14285714, 10.5       , 11.85714286, 13.21428571,
        14.57142857, 15.92857143, 17.28571429, 18.64285714, 20.        ]),
 1.3571428571428572)

In [11]:
# 4. np.zeros()
x4 = np.zeros(5)

In [12]:
x4

array([0., 0., 0., 0., 0.])

In [13]:
x4 = np.zeros((4,5))

In [14]:
x4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
# 5. np.ones()
x5 = np.ones(5)

In [17]:
x5

array([1., 1., 1., 1., 1.])

In [18]:
x5 = np.ones((4,4))

In [19]:
x5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.zeros_like(x_2d)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [27]:
np.empty((4,4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
# will return a random number b/w 0 to 1
np.random.random()

0.3921765966448352

In [29]:
np.random.random(4)

array([0.2975975 , 0.20749144, 0.37639235, 0.8673421 ])

In [30]:
np.random.random((4,4))

array([[0.04986183, 0.75515299, 0.73386403, 0.43568353],
       [0.42037061, 0.33636531, 0.64792288, 0.3154525 ],
       [0.5967104 , 0.21899295, 0.02882804, 0.52591382],
       [0.00101823, 0.65317998, 0.01205747, 0.34244978]])

In [32]:
# normal distribution
np.random.randn(4,4)

array([[-1.66022984, -1.86264122,  1.04209225,  0.14682037],
       [-1.72364389,  0.3116361 , -0.06928239,  1.34080269],
       [-0.5883971 ,  0.03341257, -0.16250285,  0.25524553],
       [ 1.76940319, -2.98439714, -1.28232972, -1.34524746]])

In [33]:
np.random.randint(1,10)

9

In [34]:
np.random.randint(1,10,7)

array([8, 3, 9, 1, 9, 7, 9])

In [35]:
np.random.randint(1,10,(5,5))

array([[6, 7, 4, 2, 8],
       [3, 5, 4, 5, 8],
       [4, 5, 7, 1, 2],
       [8, 9, 9, 8, 5],
       [7, 3, 6, 6, 4]])

In [38]:
np.random.randint(-10,10,(5,5))

array([[  6,   0,  -6,   2,   6],
       [  2, -10,   6,  -3,  -4],
       [ -5,   0,   4,  -2,  -4],
       [  0,   7,   6,  -3,   3],
       [  1,  -2,   8,  -5,   4]])