In [1]:
import numpy as np

In [2]:
x = np.random.randint(1,50,15)

In [3]:
x

array([ 9, 13,  3,  9, 29,  9, 34,  7, 22,  4, 16,  4, 42, 36,  8])

In [4]:
x.shape

(15,)

In [5]:
x = np.random.randint(1,50,(4,6))

In [6]:
x

array([[16, 13,  3,  4,  5, 20],
       [19, 21, 12, 47, 11, 40],
       [25, 42, 18, 19, 10, 30],
       [40, 27,  3, 32, 48, 27]])

In [7]:
x.shape

(4, 6)

In [8]:
x.ndim

2

In [9]:
# converts 2D to 1D
x.flatten()

array([16, 13,  3,  4,  5, 20, 19, 21, 12, 47, 11, 40, 25, 42, 18, 19, 10,
       30, 40, 27,  3, 32, 48, 27])

In [10]:
# transpose of data
x.T

array([[16, 19, 25, 40],
       [13, 21, 42, 27],
       [ 3, 12, 18,  3],
       [ 4, 47, 19, 32],
       [ 5, 11, 10, 48],
       [20, 40, 30, 27]])

In [11]:
x.reshape(6,4)

array([[16, 13,  3,  4],
       [ 5, 20, 19, 21],
       [12, 47, 11, 40],
       [25, 42, 18, 19],
       [10, 30, 40, 27],
       [ 3, 32, 48, 27]])

In [12]:
x.reshape(8,3)

array([[16, 13,  3],
       [ 4,  5, 20],
       [19, 21, 12],
       [47, 11, 40],
       [25, 42, 18],
       [19, 10, 30],
       [40, 27,  3],
       [32, 48, 27]])

In [13]:
x.reshape(3,8)

array([[16, 13,  3,  4,  5, 20, 19, 21],
       [12, 47, 11, 40, 25, 42, 18, 19],
       [10, 30, 40, 27,  3, 32, 48, 27]])

In [14]:
x.reshape(2,12)

array([[16, 13,  3,  4,  5, 20, 19, 21, 12, 47, 11, 40],
       [25, 42, 18, 19, 10, 30, 40, 27,  3, 32, 48, 27]])

In [15]:
x.reshape(4,-1)

array([[16, 13,  3,  4,  5, 20],
       [19, 21, 12, 47, 11, 40],
       [25, 42, 18, 19, 10, 30],
       [40, 27,  3, 32, 48, 27]])

In [16]:
x.reshape(-1,12)

array([[16, 13,  3,  4,  5, 20, 19, 21, 12, 47, 11, 40],
       [25, 42, 18, 19, 10, 30, 40, 27,  3, 32, 48, 27]])

In [18]:
x = x.flatten()

In [19]:
x

array([16, 13,  3,  4,  5, 20, 19, 21, 12, 47, 11, 40, 25, 42, 18, 19, 10,
       30, 40, 27,  3, 32, 48, 27])

In [20]:
np.mean(x)

22.166666666666668

In [21]:
np.var(x)

184.4722222222222

In [22]:
np.median(x)

19.5

In [23]:
np.std(x)

13.582055154586223

In [24]:
np.min(x)

3

In [25]:
np.max(x)

48

In [26]:
np.sort(x)

array([ 3,  3,  4,  5, 10, 11, 12, 13, 16, 18, 19, 19, 20, 21, 25, 27, 27,
       30, 32, 40, 40, 42, 47, 48])

In [27]:
np.sum(x)

532

In [28]:
x

array([16, 13,  3,  4,  5, 20, 19, 21, 12, 47, 11, 40, 25, 42, 18, 19, 10,
       30, 40, 27,  3, 32, 48, 27])

In [29]:
np.min(x)

3

In [30]:
np.argmin(x)

2

In [31]:
np.max(x)

48

In [32]:
np.argmax(x)

22

In [33]:
np.argsort(x)

array([ 2, 20,  3,  4, 16, 10,  8,  1,  0, 14,  6, 15,  5,  7, 12, 19, 23,
       17, 21, 18, 11, 13,  9, 22], dtype=int64)

In [34]:
x = x.reshape(4,-1)

In [35]:
x

array([[16, 13,  3,  4,  5, 20],
       [19, 21, 12, 47, 11, 40],
       [25, 42, 18, 19, 10, 30],
       [40, 27,  3, 32, 48, 27]])

In [37]:
# axis - 0 (column wise)
np.mean(x,axis=0)

array([25.  , 25.75,  9.  , 25.5 , 18.5 , 29.25])

In [38]:
# axis - 1 (row wise)
np.mean(x,axis=1)

array([10.16666667, 25.        , 24.        , 29.5       ])

In [39]:
np.sum(x, axis=0)

array([100, 103,  36, 102,  74, 117])

In [40]:
np.sum(x, axis=1)

array([ 61, 150, 144, 177])