In [1]:
import numpy as np
import sys
import time

In [2]:
np.array([2,32,4,56,7,8,3,34,23,6])

array([ 2, 32,  4, 56,  7,  8,  3, 34, 23,  6])

In [3]:
np.array([3,2,4,45,56,67,54,43,32,2,'hello'])

array(['3', '2', '4', '45', '56', '67', '54', '43', '32', '2', 'hello'],
      dtype='<U11')

In [4]:
np.array([1,3,4,5,3,3,5,6,7,8,34.5,43.56])

array([ 1.  ,  3.  ,  4.  ,  5.  ,  3.  ,  3.  ,  5.  ,  6.  ,  7.  ,
        8.  , 34.5 , 43.56])

In [5]:
np.array([3,2,4,56,7,3,True])

array([ 3,  2,  4, 56,  7,  3,  1])

In [6]:
sys.getsizeof(list())

56

In [8]:
sys.getsizeof(np.array([]))

96

In [13]:
x = list(range(3000))
sys.getsizeof(x)

24056

In [14]:
x = np.array(list(range(3000)))
sys.getsizeof(x)

12096

In [17]:
x1 = list(range(10000000))
x2 = list(range(10000000))
x3 = []

start = time.time()
for i in range(len(x1)):
    x3.append(x1[i] + x2[i])

end = time.time()
total = end - start
print("Total time taken is",total)

Total time taken is 4.298279047012329


In [18]:
x1 = np.array(list(range(10000000)))
x2 = np.array(list(range(10000000)))

start = time.time()
x3 = x1 + x2
end = time.time()
total = end - start
print("Total time taken is",total)

Total time taken is 0.24933671951293945
