In [1]:
import pandas as pd
import numpy as np
import pickle as pkl

In [41]:
age = 45
gender = 'Female'
fever = 100
bodyPain = 0
runny_nose = 1
difficult_breathing = 1
nasal_congestion = 0
sore_throat = 0
severity = 'Severe'
contact = 'no'

In [42]:
file = open('label_1.pkl', 'rb')
gender_label = pkl.load(file)
file.close()

file = open('label_2.pkl', 'rb')
severity_label = pkl.load(file)
file.close()

file = open('label_3.pkl', 'rb')
contact_label = pkl.load(file)
file.close()

In [43]:
file = open('onehot_1.pkl', 'rb')
onehot_1 = pkl.load(file)
file.close()

file = open('onehot_2.pkl', 'rb')
onehot_2 = pkl.load(file)
file.close()

file = open('onehot_3.pkl', 'rb')
onehot_3 = pkl.load(file)
file.close()

In [44]:
file = open('minmax.pkl', 'rb')
minmax = pkl.load(file)
file.close()

In [45]:
file = open('covid_model.pkl', 'rb')
logistic = pkl.load(file)
file.close()

In [46]:
gender_label.transform([gender])

array([0], dtype=int64)

In [47]:
severity_label.transform([severity])

array([2], dtype=int64)

In [48]:
gender_array = onehot_1.transform(gender_label.transform([gender]).reshape(-1,1)).toarray()

In [49]:
severity_array = onehot_2.transform(severity_label.transform([severity]).reshape(-1,1)).toarray()

In [50]:
contact_array = onehot_3.transform(contact_label.transform([contact]).reshape(-1,1)).toarray()

In [51]:
X = np.array([[age,fever,bodyPain,runny_nose,difficult_breathing, nasal_congestion,
              sore_throat]])

In [52]:
X = np.c_[X, gender_array, severity_array, contact_array]

In [53]:
X = minmax.transform(X)

In [54]:
logistic.predict(X)

array([0], dtype=int64)